### ISSUE TITLE
build problem on windows

### ISSUE THREAD

**Issue by fededed56** [xingji-studio/OpenXSKernel#2]
在Windows上，编译bootx64.c时会报指针类型不符的错误

**Comment by GuoqiFish** [comment]
您好！我们这边编译是没有报错的。如果方便的话麻烦发一下具体行数、编译工具以及截图等相关信息方便我们排查问题。谢谢！或者您也可以直接加我扣扣：1559689519。

**Comment by fededed56** [comment]
![image](https://github.com/user-attachments/assets/23a630a3-c7fb-42e9-8fb0-5bd0d082fb1b)

**Comment by fededed56** [comment]
mingw64

**Comment by GuoqiFish** [comment]
> mingw64
> 

您好，您的问题我们应该是解决了，您可以重新clone试试。
